### ISSUE TITLE
TestNG Eclipse should "Use project TestNG jar" by default

### ISSUE THREAD

**Issue by juherr** [cbeust/testng-eclipse#122]
As TestNG jar is mandatory for compile time, TestNG Eclipse should use the same jar for runtime by default.

**Comment by missedone** [comment]
fixed in PR #143

**Comment by missedone** [comment]
Howerver, please also be aware that, the original reason to disable "use project testng jar" was to make sure the the plugin embedded testng jar be compatible with the runtime testng, as plugin launch the test suite with remotetestng class, that said plugin acts as the client that receive result from testng server.

**Comment by missedone** [comment]
Now by enabling use project jar by default will expose the potential compatibility risk in future

**Comment by karl368** [comment]
I may encounter the issue missedone said just now. Even a single System.out.println("something"); statement will produce "Software caused connection abort: socket write error" error. And this issue just go if I uncheck the "Use project TestNG jar" checkbox. 

Still not know why this should happens...

**Comment by cbeust** [comment]
@karl368 Make sure you have "Use project testng.jar" NOT checked.
