### ISSUE TITLE
TestNG : Exception in thread "main" java.lang.NoSuchMethodError:

### ISSUE THREAD

**Issue by krabhishek30** [cbeust/testng-eclipse#267]
I  recently installed TestNG for Eclipse via the Eclipse Market Place and while running the code i keep getting this error information :

Exception in thread "main" java.lang.NoSuchMethodError: org.testng.internal.Utils.defaultIfStringEmpty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
    at org.testng.remote.AbstractRemoteTestNG.setHost(AbstractRemoteTestNG.java:59)
    at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
    at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)

i searched through threads here and found out that i need to install the latest plugin.
Since I downloaded from Market Place i believe the plugin should be the latest one, but stiil I am getting this issue.

**Comment by cbeust** [comment]
@missedone Any thoughts?

**Comment by missedone** [comment]
hi @krabhishek30

which testng version you used in the project?

could you install the latest beta plugin: http://testng.org/eclipse-beta (see installation detail [here](http://testng.org/doc/download.html)
i suspect you're using an older version (< 6.5.1), the new plugin will give you a more meaningful message.

**Comment by missedone** [comment]
@krabhishek30 

OK, i'm pretty sure you're using a version < 6.5.1, could you update your testng version >= 6.5.1 ?
thanks

**Comment by krabhishek30** [comment]
@missedone I used the market place to install the plugin (I believe it installs the latest version) .. I even installed  the beta version and everytime it gave me this error info.

**Comment by krabhishek30** [comment]
@messidone I believe the plugin version was 6.9 something, I can be exactly sure only in the morning(it's 1 am in the morning here)

**Comment by missedone** [comment]
hi @krabhishek30 

i meant to update your testng jar version of your project.

**Comment by krabhishek30** [comment]
@missedone yup that worked.
I used the 6.8 version and it worked fine.

Thank you.

**Comment by missedone** [comment]
ok, good to know 😄

**Comment by rajtester** [comment]
I am facing the same error. Tried Mars / Neon with 6.9.11 / 6.9.12 also.

Exception in thread "main" java.lang.NoSuchMethodError: org.testng.internal.Utils.defaultIfStringEmpty(Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
	at org.testng.remote.AbstractRemoteTestNG.setHost(AbstractRemoteTestNG.java:59)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:122)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

**Comment by missedone** [comment]
hi @rajtester 
what's the version of TestNG Eclipse Plugin you used?
could you confirm there is only one testng jar on your classpath?

**Comment by rajtester** [comment]
I tried both TestNG 6.9.11 & 6.9.12 also. I have added some more jars for selenium including testng.

**Comment by missedone** [comment]
could you confirm that the plugin you used is latest release `6.9.12.201607091356`, or even you can try with the latest beta http://testng.org/eclipse-beta

> I have added some more jars for selenium including testng.

I know that selenium has a fat jar has testng embedded in it. could you make sure there is only one testng on your classpath, either the fat jar of selenium or the stock testng jar.

**Comment by rajtester** [comment]
Thanks a lot Nick (missedone). It worked. There was a mismatch with TestNG version.

**Comment by dassusovan** [comment]
im using TestNG version 6.8.2

java.lang.NoSuchMethodError: org.testng.internal.IConfiguration.getConfigurationListeners()Ljava/util/List;
	at org.testng.remote.support.RemoteTestNG6_5$1.newTestRunner(RemoteTestNG6_5.java:34)
	at org.testng.remote.support.RemoteTestNG6_5$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_5.java:63)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:544)
	at org.testng.SuiteRunner.init(SuiteRunner.java:142)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:106)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1116)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1103)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:955)
	at org.testng.TestNG.run(TestNG.java:900)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by missedone** [comment]
@dassusovan 
where do you get this 6.8.2 release?
i don't even see it on Maven central:
![image](https://user-images.githubusercontent.com/555134/53220926-d8279380-361b-11e9-913c-4d7f29440fba.png)
https://search.maven.org/search?q=g:org.testng%20AND%20a:testng&core=gav

**Comment by Anjaneyan** [comment]
if your frame using pom.xml , make sure pom.xml and eclipse market place has the same version of TestNG. 
Usually you will get the below error if these jar files are different versions.
e.g: 
-pom.xml has <version>6.13.1</version>
-eclipse market place has <version>6.9.10</version>
Error:
java.lang.NoSuchMethodError: org.testng.TestRunner.addListener(Ljava/lang/Object;)V
at rg.testng.remote.support.RemoteTestNG6_9_10$1.newTestRunner(RemoteTestNG6_9_10.java:32)

Note: To get resolve your problem update TestNG version in pom.xml , from <version>6.13.1</version> to <version>6.9.10</version>

**Comment by shashankhnqa** [comment]
java.lang.NoSuchMethodError: org.testng.TestRunner.addListener(Ljava/lang/Object;)V
	at org.testng.remote.support.RemoteTestNG6_9_10$1.newTestRunner(RemoteTestNG6_9_10.java:32)
	at org.testng.remote.support.RemoteTestNG6_9_10$DelegatingTestRunnerFactory.newTestRunner(RemoteTestNG6_9_10.java:61)
	at org.testng.SuiteRunner$ProxyTestRunnerFactory.newTestRunner(SuiteRunner.java:713)
	at org.testng.SuiteRunner.init(SuiteRunner.java:260)
	at org.testng.SuiteRunner.<init>(SuiteRunner.java:198)
	at org.testng.TestNG.createSuiteRunner(TestNG.java:1295)
	at org.testng.TestNG.createSuiteRunners(TestNG.java:1273)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1128)
	at org.testng.TestNG.runSuites(TestNG.java:1049)
	at org.testng.TestNG.run(TestNG.java:1017)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)

**Comment by shashankhnqa** [comment]
same issue with testng 6.14.3 version...please help guys

**Comment by akshay201190** [comment]
yes same issue on 6.14.3 version.

java.lang.NoSuchMethodError: org.testng.TestRunner.addListener(Ljava/lang/Object;)V

In one project, tests successfully run by testng.xml but other it is not.

Using same version(6.14.3) testng version in my pom.xml

**Comment by shashankhnqa** [comment]
I have tried removing the eclipse & java from the system & reinstalling the eclipse,java & testng, issue got resoved. It works.

**Comment by akshay201190** [comment]
But in my one project, it's working using the same eclipse

**Comment by vishaalcbe** [comment]
Hi All,
I have created a maven testng project. I'm able to run and test using Maven by providing the testng.xml file in </suiteXmlFile> tags. But when I try to test the class as a testng test, I end up getting the below error.

[RemoteTestNG] detected TestNG version 7.0.0
java.lang.NoSuchMethodError: org.testng.remote.AbstractRemoteTestNG.addListener(Lorg/testng/ISuiteListener;)V
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

**Comment by mjuneja123** [comment]
I was facing the same issue, and then replacing the old testNG jar file (6.14.2) with the latest version (7.0.0) solved my problem.

**Comment by genesisa96** [comment]
Hi can someone help me with this, I've tried every solution there is but nothing works
[RemoteTestNG] detected TestNG version 7.0.1
Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:17)
	at org.testng.remote.support.RemoteTestNG6_12.<init>(RemoteTestNG6_12.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	at java.net.URLClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	... 7 more

**Comment by missedone** [comment]
@genesisa96 i think it's different issue as of this ticket.
but same as what i reported https://github.com/cbeust/testng/issues/2223

**Comment by rahulmogar** [comment]
remove jar files from the build path , and install testng from install software in help menu
worked for me

**Comment by gauravpratap01** [comment]
> Hi can someone help me with this, I've tried every solution there is but nothing works
> **[RemoteTestNG] detected TestNG version 7.0.1**
> Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
> at org.testng.internal.Configuration.(Configuration.java:33)
> at org.testng.TestNG.init(TestNG.java:216)
> at org.testng.TestNG.(TestNG.java:200)
> at org.testng.remote.AbstractRemoteTestNG.(AbstractRemoteTestNG.java:17)
> at org.testng.remote.support.RemoteTestNG6_12.(RemoteTestNG6_12.java:18)
> at org.testng.remote.support.RemoteTestNGFactory6_12.createRemoteTestNG(RemoteTestNGFactory6_12.java:16)
> at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:67)
> Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
> ... 7 more
> Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
> at java.net.URLClassLoader.findClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
> at java.lang.ClassLoader.loadClass(Unknown Source)
> ... 7 more

I am also getting the same error. Actually first i have added TestNG jar file in build path but i was not getting option in "Run configuration" , run as TestNG file.
So i have install the plugin. Now i am getting option Run as TestNG file but getting the above mentioned error.
Can you please help.

**Comment by missedone** [comment]
Hi as a workaround, you can add guide jar to your project classpath.

**Comment by gauravpratap01** [comment]
What is guide jar?

**Comment by missedone** [comment]
if your project dependency is managed with Maven, you can try to add the following `guice` jar to pom.xml:
```
<dependency>
  <groupId>com.google.inject</groupId>
  <artifactId>guice</artifactId>
  <version>4.1.0</version>
  <classifier>no_aop</classifier>
</dependency>
```

**Comment by gauravpratap01** [comment]
Thanks for the workaround Nick.
But i don't want to use Maven dependency in the project. I just want to use TestNG jar.
Any other method? If i directly want to run through TestNG

**Comment by gauravpratap01** [comment]
Nick, i wanted to give it a try again to fix this with below steps-
1) I have removed the TestNG jars
2) Now i have reloaded the plugin again from "Install New software" in eclipse
3) Then i've added the TestNG jar again in the project
But still getting below error first-

Error pop up: A JNI error has occurred, please check your installation and try again

**Then getting below error-**

Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
	at java.lang.Class.getDeclaredMethods0(Native Method)
	at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
	at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
	at java.lang.Class.getMethod0(Class.java:3018)
	at java.lang.Class.getMethod(Class.java:1784)
	at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

**Comment by missedone** [comment]
@gauravpratap01 , it's fixed in testng 7.2.0, pls check my comment: https://github.com/cbeust/testng-eclipse/issues/472#issuecomment-599251156

**Comment by ST394157** [comment]
> Nick, i wanted to give it a try again to fix this with below steps-
> 
> 1. I have removed the TestNG jars
> 2. Now i have reloaded the plugin again from "Install New software" in eclipse
> 3. Then i've added the TestNG jar again in the project
>    But still getting below error first-
> 
> Error pop up: A JNI error has occurred, please check your installation and try again
> 
> **Then getting below error-**
> 
> Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
> at java.lang.Class.getDeclaredMethods0(Native Method)
> at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
> at java.lang.Class.getMethod0(Class.java:3018)
> at java.lang.Class.getMethod(Class.java:1784)
> at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
> at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
> Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
> at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> ... 7 more

Please import jcommander jar from maven. Then it will work

**Comment by pankajdandge** [comment]
> > Nick, i wanted to give it a try again to fix this with below steps-
> > 
> > 1. I have removed the TestNG jars
> > 2. Now i have reloaded the plugin again from "Install New software" in eclipse
> > 3. Then i've added the TestNG jar again in the project
> >    But still getting below error first-
> > 
> > Error pop up: A JNI error has occurred, please check your installation and try again
> > **Then getting below error-**
> > Exception in thread "main" java.lang.NoClassDefFoundError: com/beust/jcommander/ParameterException
> > at java.lang.Class.getDeclaredMethods0(Native Method)
> > at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
> > at java.lang.Class.privateGetMethodRecursive(Class.java:3048)
> > at java.lang.Class.getMethod0(Class.java:3018)
> > at java.lang.Class.getMethod(Class.java:1784)
> > at sun.launcher.LauncherHelper.validateMainClass(LauncherHelper.java:544)
> > at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:526)
> > Caused by: java.lang.ClassNotFoundException: com.beust.jcommander.ParameterException
> > at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
> > at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
> > at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
> > ... 7 more
> 
> Please import jcommander jar from maven. Then it will work

yes this is work for me but after adding the jar file getting the previous error

**Error** : "Exception in thread "main" java.lang.BootstrapMethodError: java.lang.NoClassDefFoundError: com/google/inject/Stage
	at org.testng.internal.Configuration.<init>(Configuration.java:33)
	at org.testng.TestNG.init(TestNG.java:216)
	at org.testng.TestNG.<init>(TestNG.java:200)
	at org.testng.remote.AbstractRemoteTestNG.<init>(AbstractRemoteTestNG.java:21)
	at org.testng.remote.support.RemoteTestNG6_9_10.<init>(RemoteTestNG6_9_10.java:18)
	at org.testng.remote.support.RemoteTestNGFactory6_9_10.createRemoteTestNG(RemoteTestNGFactory6_9_10.java:16)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:42)
Caused by: java.lang.NoClassDefFoundError: com/google/inject/Stage
	... 7 more
Caused by: java.lang.ClassNotFoundException: com.google.inject.Stage
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 7 more

"

**Comment by missedone** [comment]
@pankajdandge , the root cause of this issue is in the testng.jar. to fix the issue is simply update the testng-p2 plugin (which is another eclipse plugin used by testng eclipse plugin)
the updatesite of testng-p2 is: https://dl.bintray.com/testng-team/testng-p2-release/7.2.0/
details steps: 
1) open eclipse, 2) navigate the menu bar "Help" -> "Install New Software..." -> paste the testng-p2 update site url in the "Work with: " text field. -> follow the instruction to install.

also it's recommended to install the latest testng eclipse plugin: https://dl.bintray.com/testng-team/testng-eclipse-release/updatesites/7.2.0.202005051752/

**Comment by Geethu2593-GIT** [comment]
I'm still facing the same issue.

[RemoteTestNG] detected TestNG version 7.0.0
Exception in thread "main" java.lang.NoSuchMethodError: org.testng.TestNG.configure(Lorg/testng/CommandLineArgs;)V
	at org.testng.remote.AbstractRemoteTestNG.configure(AbstractRemoteTestNG.java:75)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:235)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)

I tried to match all the verion plugin and testng jar


For testNG p2-  i used this urlhttps://dl.bintray.com/testng-team/testng-p2-release/7.2.0/

**Comment by anishbabus** [comment]
I tried the below solution and it worked for me
Add the TestNG Library into the project.
1. Right Click on the Project
2. Build Path
3. Configure Build Path
4. Libraries (Tab)
5. Go to "Add Library" and click the button.
6. Add the 'TestNG' Library and apply and close.

Try running again.

**Comment by Brijesh-Yadav** [comment]
**Problem Statement**  TestNG : Exception in thread "main" java.lang.NoSuchMethodError: is coming

I was facing the same issue. Below is mine incident

1. - I created maven project and i added testng 7.0.1 dependencies in pom.xml
2. - Also i installed TestNG library from Eclipse MarketPlace
whenever I run it was throwing the above error.

**Solution** 
I removed testng dependencies from pom.xml file
I added testng library then imported all lib in test script classes.

After that i didn't face the above problem

Hope that will help.
-

**Comment by ritugakher** [comment]
> 
> 
> I tried the below solution and it worked for me
> Add the TestNG Library into the project.
> 
>     1. Right Click on the Project
> 
>     2. Build Path
> 
>     3. Configure Build Path
> 
>     4. Libraries (Tab)
> 
>     5. Go to "Add Library" and click the button.
> 
>     6. Add the 'TestNG' Library and apply and close.
> 
> 
> Try running again.

thanks! It worked for me.

**Comment by eluemeln** [comment]
create your file through TestNG
not the normal way

**Comment by eluemeln** [comment]
the class should be  a TestNG class

**Comment by gharatla** [comment]
> jcommander

jcommander jar is missing which is required to run Rest Assured with TestNG
